### ISSUE TITLE
Trouble with audiosink on raspberry pi

### ISSUE THREAD

**Issue by nettnikl** [hzeller/gmrender-resurrect#243]
## Error
On current Docker image running on a manjaro based Raspberry Pi 4.
The relevant part of the docker compose file.
Dockerfile can be found here https://github.com/leakypixel/dockerfiles/blob/master/gmrender/Dockerfile.
```
        devices:
            - /dev/snd:/dev/snd
        environment:
            - 'DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket'
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/run/dbus/system_bus_socket:/run/dbus/system_bus_socket' # For avahi publishing
            - '/etc/machine-id:/etc/machine-id:ro'
            #- './asound.conf:/etc/asound.conf'
        entrypoint: gmediarender
        command: ["--gstout-audiosink=alsasink --gstout-audiodevice=default:CARD=Headphones", "--logfile=stdout"]

```
```
gmrender  | AL lib: (EE) ALCplaybackAlsa_reset: snd_pcm_hw_params(self->pcmHandle, hp) failed: File descriptor in bad state
gmrender  | ERROR [2022-01-02 02:38:04.734312 | gstreamer] audiosink-actual-sink-openal: Error: Unable to prepare device. (Debug: ../ext/openal/gstopenalsink.c(858): gst_openal_sink_prepare (): /GstPlayBin:play/GstPlaySink:playsink/GstBin:abin/GstAutoAudioSink:audiosink/GstOpenALSink:audiosink-actual-sink-openal:
gmrender  | ALC error: Invalid Device)
gmrender  | ERROR [2022-01-02 02:38:04.735268 | gstreamer] audiosink-actual-sink-openal: Error: The stream is in the wrong format. (Debug: ../gst-libs/gst/audio/gstaudiobasesink.c(1191): gst_audio_base_sink_preroll (): /GstPlayBin:play/GstPlaySink:playsink/GstBin:abin/GstAutoAudioSink:audiosink/GstOpenALSink:audiosink-actual-sink-openal:
gmrender  | sink not negotiated.)
gmrender  | ERROR [2022-01-02 02:38:04.736202 | gstreamer] source: Error: Internal data stream error. (Debug: ../libs/gst/base/gstbasesrc.c(3127): gst_base_src_loop (): /GstPlayBin:play/GstURIDecodeBin:uridecodebin0/GstSoupHTTPSrc:source:
gmrender  | streaming stopped, reason not-negotiated (-4))
```
## What i tried
Running `aplay CantinaBand3.wav -D default:CARD=Headphones` inside the container works just fine, however gstreamer and/or gmrender does not. Should this work: `gst-play-1.0 sample.wav --audiosink=alsasink`? What am i doing wrong here?
